// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadFlowEvents returns the embedded CollectionSpec for flowEvents.
func loadFlowEvents() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlowEventsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load flowEvents: %w", err)
	}

	return spec, err
}

// loadFlowEventsObjects loads flowEvents and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*flowEventsObjects
//	*flowEventsPrograms
//	*flowEventsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFlowEventsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFlowEvents()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// flowEventsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowEventsSpecs struct {
	flowEventsProgramSpecs
	flowEventsMapSpecs
}

// flowEventsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowEventsProgramSpecs struct {
	HandleInetSockSetState *ebpf.ProgramSpec `ebpf:"handle_inet_sock_set_state"`
}

// flowEventsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowEventsMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// flowEventsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFlowEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowEventsObjects struct {
	flowEventsPrograms
	flowEventsMaps
}

func (o *flowEventsObjects) Close() error {
	return _FlowEventsClose(
		&o.flowEventsPrograms,
		&o.flowEventsMaps,
	)
}

// flowEventsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFlowEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowEventsMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *flowEventsMaps) Close() error {
	return _FlowEventsClose(
		m.Events,
	)
}

// flowEventsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFlowEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowEventsPrograms struct {
	HandleInetSockSetState *ebpf.Program `ebpf:"handle_inet_sock_set_state"`
}

func (p *flowEventsPrograms) Close() error {
	return _FlowEventsClose(
		p.HandleInetSockSetState,
	)
}

func _FlowEventsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flowevents_x86_bpfel.o
var _FlowEventsBytes []byte
