// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type flowEventsFlowConfig struct {
	TlsHandshakeInspectEnabled uint8
	Pad                        [7]uint8
}

type flowEventsFlowKey struct {
	SrcIp     uint32
	DstIp     uint32
	SrcPort   uint16
	DstPort   uint16
	Protocol  uint8
	Direction uint8
	Pad0      uint16
}

type flowEventsFlowStats struct {
	StartNs                    uint64
	LastSeenNs                 uint64
	LastEmitNs                 uint64
	CgroupId                   uint64
	NetnsIno                   uint64
	BytesSent                  uint64
	BytesRecv                  uint64
	PacketsSent                uint64
	PacketsRecv                uint64
	PktSizeBuckets             [7]uint64
	IatBuckets                 [6]uint64
	PktSizeMin                 uint64
	PktSizeMax                 uint64
	IdleGapCount               uint64
	BurstCount                 uint64
	RealPacketsSent            uint64
	RealPacketsRecv            uint64
	LastPacketNsSent           uint64
	LastPacketNsRecv           uint64
	SynCount                   uint32
	FinCount                   uint32
	RstCount                   uint32
	CloseSeen                  uint8
	ClientHelloInspected       uint8
	ServerHelloInspected       uint8
	TrafficAccountingAvailable uint8
	PacketTimingAvailable      uint8
	TcpMetricsAvailable        uint8
	Pad1                       [2]uint8
	_                          [4]byte
}

// loadFlowEvents returns the embedded CollectionSpec for flowEvents.
func loadFlowEvents() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlowEventsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load flowEvents: %w", err)
	}

	return spec, err
}

// loadFlowEventsObjects loads flowEvents and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*flowEventsObjects
//	*flowEventsPrograms
//	*flowEventsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFlowEventsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFlowEvents()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// flowEventsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowEventsSpecs struct {
	flowEventsProgramSpecs
	flowEventsMapSpecs
}

// flowEventsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowEventsProgramSpecs struct {
	HandleCgroupSkbEgress  *ebpf.ProgramSpec `ebpf:"handle_cgroup_skb_egress"`
	HandleCgroupSkbIngress *ebpf.ProgramSpec `ebpf:"handle_cgroup_skb_ingress"`
	HandleInetSockSetState *ebpf.ProgramSpec `ebpf:"handle_inet_sock_set_state"`
	HandleTcpRecvmsgEntry  *ebpf.ProgramSpec `ebpf:"handle_tcp_recvmsg_entry"`
	HandleTcpRecvmsgReturn *ebpf.ProgramSpec `ebpf:"handle_tcp_recvmsg_return"`
	HandleTcpSendmsg       *ebpf.ProgramSpec `ebpf:"handle_tcp_sendmsg"`
}

// flowEventsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowEventsMapSpecs struct {
	ConfigMap          *ebpf.MapSpec `ebpf:"config_map"`
	DropCounters       *ebpf.MapSpec `ebpf:"drop_counters"`
	Events             *ebpf.MapSpec `ebpf:"events"`
	FlowStatsMap       *ebpf.MapSpec `ebpf:"flow_stats_map"`
	RecvArgsMap        *ebpf.MapSpec `ebpf:"recv_args_map"`
	TlsHandshakeEvents *ebpf.MapSpec `ebpf:"tls_handshake_events"`
}

// flowEventsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFlowEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowEventsObjects struct {
	flowEventsPrograms
	flowEventsMaps
}

func (o *flowEventsObjects) Close() error {
	return _FlowEventsClose(
		&o.flowEventsPrograms,
		&o.flowEventsMaps,
	)
}

// flowEventsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFlowEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowEventsMaps struct {
	ConfigMap          *ebpf.Map `ebpf:"config_map"`
	DropCounters       *ebpf.Map `ebpf:"drop_counters"`
	Events             *ebpf.Map `ebpf:"events"`
	FlowStatsMap       *ebpf.Map `ebpf:"flow_stats_map"`
	RecvArgsMap        *ebpf.Map `ebpf:"recv_args_map"`
	TlsHandshakeEvents *ebpf.Map `ebpf:"tls_handshake_events"`
}

func (m *flowEventsMaps) Close() error {
	return _FlowEventsClose(
		m.ConfigMap,
		m.DropCounters,
		m.Events,
		m.FlowStatsMap,
		m.RecvArgsMap,
		m.TlsHandshakeEvents,
	)
}

// flowEventsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFlowEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowEventsPrograms struct {
	HandleCgroupSkbEgress  *ebpf.Program `ebpf:"handle_cgroup_skb_egress"`
	HandleCgroupSkbIngress *ebpf.Program `ebpf:"handle_cgroup_skb_ingress"`
	HandleInetSockSetState *ebpf.Program `ebpf:"handle_inet_sock_set_state"`
	HandleTcpRecvmsgEntry  *ebpf.Program `ebpf:"handle_tcp_recvmsg_entry"`
	HandleTcpRecvmsgReturn *ebpf.Program `ebpf:"handle_tcp_recvmsg_return"`
	HandleTcpSendmsg       *ebpf.Program `ebpf:"handle_tcp_sendmsg"`
}

func (p *flowEventsPrograms) Close() error {
	return _FlowEventsClose(
		p.HandleCgroupSkbEgress,
		p.HandleCgroupSkbIngress,
		p.HandleInetSockSetState,
		p.HandleTcpRecvmsgEntry,
		p.HandleTcpRecvmsgReturn,
		p.HandleTcpSendmsg,
	)
}

func _FlowEventsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flowevents_arm64_bpfel.o
var _FlowEventsBytes []byte
