// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type flowEventsFlowKey struct {
	SrcIp     uint32
	DstIp     uint32
	SrcPort   uint16
	DstPort   uint16
	Protocol  uint8
	Direction uint8
	Pad0      uint16
	CgroupId  uint64
}

type flowEventsFlowStats struct {
	StartNs                    uint64
	LastSeenNs                 uint64
	LastEmitNs                 uint64
	BytesSent                  uint64
	BytesRecv                  uint64
	PacketsSent                uint64
	PacketsRecv                uint64
	SynCount                   uint32
	FinCount                   uint32
	RstCount                   uint32
	CloseSeen                  uint8
	TrafficAccountingAvailable uint8
	TcpMetricsAvailable        uint8
	Pad1                       uint8
}

// loadFlowEvents returns the embedded CollectionSpec for flowEvents.
func loadFlowEvents() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlowEventsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load flowEvents: %w", err)
	}

	return spec, err
}

// loadFlowEventsObjects loads flowEvents and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*flowEventsObjects
//	*flowEventsPrograms
//	*flowEventsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFlowEventsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFlowEvents()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// flowEventsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowEventsSpecs struct {
	flowEventsProgramSpecs
	flowEventsMapSpecs
}

// flowEventsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowEventsProgramSpecs struct {
	HandleInetSockSetState *ebpf.ProgramSpec `ebpf:"handle_inet_sock_set_state"`
	HandleTcpRecvmsgEntry  *ebpf.ProgramSpec `ebpf:"handle_tcp_recvmsg_entry"`
	HandleTcpRecvmsgReturn *ebpf.ProgramSpec `ebpf:"handle_tcp_recvmsg_return"`
	HandleTcpSendmsg       *ebpf.ProgramSpec `ebpf:"handle_tcp_sendmsg"`
}

// flowEventsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowEventsMapSpecs struct {
	DropCounters *ebpf.MapSpec `ebpf:"drop_counters"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	FlowStatsMap *ebpf.MapSpec `ebpf:"flow_stats_map"`
	RecvArgsMap  *ebpf.MapSpec `ebpf:"recv_args_map"`
}

// flowEventsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFlowEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowEventsObjects struct {
	flowEventsPrograms
	flowEventsMaps
}

func (o *flowEventsObjects) Close() error {
	return _FlowEventsClose(
		&o.flowEventsPrograms,
		&o.flowEventsMaps,
	)
}

// flowEventsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFlowEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowEventsMaps struct {
	DropCounters *ebpf.Map `ebpf:"drop_counters"`
	Events       *ebpf.Map `ebpf:"events"`
	FlowStatsMap *ebpf.Map `ebpf:"flow_stats_map"`
	RecvArgsMap  *ebpf.Map `ebpf:"recv_args_map"`
}

func (m *flowEventsMaps) Close() error {
	return _FlowEventsClose(
		m.DropCounters,
		m.Events,
		m.FlowStatsMap,
		m.RecvArgsMap,
	)
}

// flowEventsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFlowEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowEventsPrograms struct {
	HandleInetSockSetState *ebpf.Program `ebpf:"handle_inet_sock_set_state"`
	HandleTcpRecvmsgEntry  *ebpf.Program `ebpf:"handle_tcp_recvmsg_entry"`
	HandleTcpRecvmsgReturn *ebpf.Program `ebpf:"handle_tcp_recvmsg_return"`
	HandleTcpSendmsg       *ebpf.Program `ebpf:"handle_tcp_sendmsg"`
}

func (p *flowEventsPrograms) Close() error {
	return _FlowEventsClose(
		p.HandleInetSockSetState,
		p.HandleTcpRecvmsgEntry,
		p.HandleTcpRecvmsgReturn,
		p.HandleTcpSendmsg,
	)
}

func _FlowEventsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flowevents_x86_bpfel.o
var _FlowEventsBytes []byte
