apiVersion: v1
kind: ServiceAccount
metadata:
  name: flow-ledger-node-agent
  namespace: flow-ledger-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flow-ledger-node-agent
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "serviceaccounts", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flow-ledger-node-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flow-ledger-node-agent
subjects:
  - kind: ServiceAccount
    name: flow-ledger-node-agent
    namespace: flow-ledger-system
